{"name": "test_redis_cache_initialization_connection_error", "status": "passed", "description": "Test RedisCache initialisatie met connection error.", "attachments": [{"name": "log", "source": "1764a7cc-1be5-44b3-975f-d657996a17b8-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3cf79da6-96b3-4a5b-80be-33295d7843dd-attachment.txt", "type": "text/plain"}], "start": 1753819436175, "stop": 1753819436176, "uuid": "85cf9a68-3d25-4793-8519-70c3b97fa7dd", "historyId": "39672108a95499f633f189674fd9d544", "testCaseId": "39672108a95499f633f189674fd9d544", "fullName": "tests.unit.core.test_redis_cache_coverage.TestRedisCacheCoverage#test_redis_cache_initialization_connection_error", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_redis_cache_coverage"}, {"name": "subSuite", "value": "TestRedisCacheCoverage"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_redis_cache_coverage"}], "titlePath": ["tests", "unit", "core", "test_redis_cache_coverage.py", "TestRedisCacheCoverage"]}