{"name": "test_global_cache_instance_exists", "status": "passed", "description": "Test dat globale cache instance bestaat.", "start": 1753819436229, "stop": 1753819436229, "uuid": "046e8567-5b62-4275-b04e-9170655e927b", "historyId": "4b13fcb568a91d0674091d21635b9674", "testCaseId": "4b13fcb568a91d0674091d21635b9674", "fullName": "tests.unit.core.test_redis_cache_coverage.TestGlobalCacheInstance#test_global_cache_instance_exists", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_redis_cache_coverage"}, {"name": "subSuite", "value": "TestGlobalCacheInstance"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_redis_cache_coverage"}], "titlePath": ["tests", "unit", "core", "test_redis_cache_coverage.py", "TestGlobalCacheInstance"]}