{"name": "test_invalid_json_structured_output", "status": "passed", "description": "Test handling of invalid JSON in structured output with cache testing.", "attachments": [{"name": "log", "source": "42081532-64a0-47c3-9fc3-4fe6d15e3fb8-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "e7df152e-b769-402a-a6bc-33cc158f9439-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a0f6e2b9-aa31-49c4-9344-21627084b571-attachment.txt", "type": "text/plain"}], "start": 1753819429078, "stop": 1753819429081, "uuid": "18d53673-8d5c-4511-9288-0dbfdd025211", "historyId": "23330854ae96fe4f68a146f9c78bf525", "testCaseId": "23330854ae96fe4f68a146f9c78bf525", "fullName": "tests.unit.core.test_llm_client_coverage.TestAskOpenAIWithConfidence#test_invalid_json_structured_output", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_llm_client_coverage"}, {"name": "subSuite", "value": "TestAskOpenAIWithConfidence"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_llm_client_coverage"}], "titlePath": ["tests", "unit", "core", "test_llm_client_coverage.py", "TestAskOpenAIWithConfidence"]}