{"name": "test_workflow_with_failure_and_retry", "status": "passed", "description": "Test workflow with task failure and retry.", "attachments": [{"name": "log", "source": "fb947e85-6820-4df0-9dd9-28de91b3f67b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "818a8ecc-82ab-4539-a387-751e5d325123-attachment.txt", "type": "text/plain"}], "start": 1753819422106, "stop": 1753819422127, "uuid": "5856a71f-9cab-4c47-9dba-91138573f5e7", "historyId": "55647924c6ec6ad6d1d3b844d147cf09", "testCaseId": "55647924c6ec6ad6d1d3b844d147cf09", "fullName": "tests.integration.workflows.test_advanced_workflow_coverage.TestWorkflowIntegration#test_workflow_with_failure_and_retry", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.integration.workflows"}, {"name": "suite", "value": "test_advanced_workflow_coverage"}, {"name": "subSuite", "value": "TestWorkflowIntegration"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.workflows.test_advanced_workflow_coverage"}], "titlePath": ["tests", "integration", "workflows", "test_advanced_workflow_coverage.py", "TestWorkflowIntegration"]}