{"name": "test_exists_with_redis_error", "status": "passed", "description": "Test exists met Redis error.", "attachments": [{"name": "log", "source": "737caf80-6617-489c-b96d-6564df356f90-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ad857264-0d5f-4976-8946-756d6437189c-attachment.txt", "type": "text/plain"}], "start": 1753819436207, "stop": 1753819436209, "uuid": "7016cf26-c6de-4041-938b-942bab5030a0", "historyId": "52dea8d067a7981fc2d4ba8b026fc9aa", "testCaseId": "52dea8d067a7981fc2d4ba8b026fc9aa", "fullName": "tests.unit.core.test_redis_cache_coverage.TestRedisCacheCoverage#test_exists_with_redis_error", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_redis_cache_coverage"}, {"name": "subSuite", "value": "TestRedisCacheCoverage"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_redis_cache_coverage"}], "titlePath": ["tests", "unit", "core", "test_redis_cache_coverage.py", "TestRedisCacheCoverage"]}