{"name": "test_architect_error_handling", "status": "passed", "description": "Test architect error handling.", "start": 1753819428756, "stop": 1753819428756, "uuid": "ee0dbeb1-fdc3-436d-be9d-b333baec8f74", "historyId": "c14e8fd6d204875d8eba88e037f76585", "testCaseId": "c14e8fd6d204875d8eba88e037f76585", "fullName": "tests.unit.core.test_agent_modules.TestArchitectAgent#test_architect_error_handling", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_agent_modules"}, {"name": "subSuite", "value": "TestArchitectAgent"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_agent_modules"}], "titlePath": ["tests", "unit", "core", "test_agent_modules.py", "TestArchitectAgent"]}